name = "MLIR"
uuid = "bfde9dd4-8f40-4a1e-be09-1475335e1c92"
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
MLIR_jll = "a70bccb4-a5c0-5e2e-a329-e731972457e8"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
ScopedValues = "7e506255-f358-4e82-b7e4-beb19740aa63"

[compat]
CEnum = "0.4"
MLIR_jll = "14,15,16,17"
Preferences = "1"
ScopedValues = "1"
julia = "1.9"
